kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: poser
servers: 1
registries:
  use:
    - k3d-registry.localhost:5000
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returining; same as `--wait` (default: true)
    timeout: "60s" # wait timeout before aborting; same as `--timeout 60s`
